version: '3.5'

networks:
  twitter-demo:
    name: twitter-demo-net
    driver: bridge

services:
  zookeeper:
    image: zookeeper:3.4.9
    ports:
      - "2181:2181"
    networks:
      - twitter-demo

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    environment:
      # KAFKA_BROKER_ID: 1
      # (Hack for Mac)use this if you want to have docker host node to be used as broadcast ip
      HOSTNAME_COMMAND: "/sbin/ip route|awk '/src/ { print $$NF }'"
      # Use below for Linux
      # HOSTNAME_COMMAND: "ip route get 1.2.3.4 | awk '{print $$7}'"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_CREATE_TOPICS: "varnish_raw_logs:10:1"
    depends_on:
      - zookeeper
    ports:
      - 9092
    networks:
      - twitter-demo
  
  #jdk container is used to run flume
  jdk:
    image: openjdk
    depends_on:
        - kafka
        - zookeeper
    volumes:
        - "./docker_share:/docker_share"
    command: 'tail -F anything'
    networks:
        - twitter-demo
  
  #elk container is used to run logstash, elasticsearch, and kibana
  elk:
    image: sebp/elk
    volumes:
      - "./docker_share:/docker_share"
    depends_on:
      - kafka
      - zookeeper
    ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
    networks:
      - twitter-demo